# Generated by Django 2.2.6 on 2022-03-14 13:38

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
