# Generated by Django 2.2.6 on 2022-03-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='typeUser',
        ),
    ]
