# Generated by Django 2.2.6 on 2022-03-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boxs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Descrição')),
                ('model', models.CharField(max_length=256, null=True, verbose_name='Modelo')),
                ('manufacturer', models.CharField(max_length=256, null=True, verbose_name='Fabricante')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Descrição')),
                ('model', models.CharField(max_length=256, null=True, verbose_name='Modelo')),
                ('manufacturer', models.CharField(max_length=256, null=True, verbose_name='Fabricante')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='Tipo')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='poles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Descrição')),
                ('model', models.CharField(max_length=256, null=True, verbose_name='Modelo')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='Tipo')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spliters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Descrição')),
                ('model', models.CharField(max_length=256, null=True, verbose_name='Modelo')),
                ('manufacturer', models.CharField(max_length=256, null=True, verbose_name='Fabricante')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='Tipo')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='steels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='Descrição')),
                ('model', models.CharField(max_length=256, null=True, verbose_name='Modelo')),
                ('manufacturer', models.CharField(max_length=256, null=True, verbose_name='Fabricante')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Preço')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
