# Generated by Django 2.2.6 on 2022-03-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipaments', '0002_auto_20220315_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poles',
            name='description',
        ),
        migrations.RemoveField(
            model_name='poles',
            name='model',
        ),
    ]
