# Generated by Django 2.2.6 on 2022-03-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipaments', '0003_auto_20220316_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='poles',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='Tipo'),
        ),
    ]
