# Generated by Django 2.2.6 on 2022-03-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipaments', '0004_poles_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poles',
            name='description',
        ),
    ]
