# Generated by Django 2.2.6 on 2022-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ceoprices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceoModel_id', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'ceoPrices',
                'managed': False,
            },
        ),
    ]
