# Generated by Django 2.2.6 on 2022-03-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ceoprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctoprices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctoModel_id', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'ctoPrices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='polepriceslocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField()),
                ('geolocation', models.CharField(max_length=256)),
                ('isLocate', models.BooleanField()),
                ('priceLocation', models.FloatField()),
            ],
            options={
                'db_table': 'polePriceLocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='spliterprices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spliter1_id', models.IntegerField()),
                ('spliter2_id', models.IntegerField()),
                ('spliter3_id', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'spliterPrices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='steelprices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelSteel_id', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'steelPrices',
                'managed': False,
            },
        ),
    ]
