# Generated by Django 2.2.6 on 2022-03-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ctoprices_polepriceslocation_spliterprices_steelprices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='polepriceslocation',
            table='polePricesLocation',
        ),
    ]
