# Generated by Django 2.2.6 on 2022-03-18 12:51

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220316_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionpoles',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100),
        ),
    ]
